listen_addresses = '*'
shared_buffers = 256MB
work_mem = 16MB
effective_cache_size = 768MB
max_connections = 100
wal_level = replica
synchronous_commit = on
log_statement = 'none'
log_min_duration_statement = 500
password_encryption = scram-sha-256
